project:
  type: website
  output-dir: docs

website:
  title: "Sarah Huet"
  site-url: "https://sarah-huet.github.io/"

  # This creates the lateral toolbar
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: cv.qmd
      - text: "FADN2Footprint"
        file: fadn2footprint.qmd
      - text: "Media"
        file: media.qmd

format:
  html:
    theme: mint # You can change this to 'cosmo', lux', 'minty', 'flatly', etc.
    css: assets/css/styles.css
    toc: true
